### PR TITLE
Use a different color scheme on dark theme

### PR DESCRIPTION
**Pull request by mozbugbox**
Add an option to use a different color scheme for the dark theme.

### CODE REVIEW

**Comment by mike-fabian** [comment]
I am testing this. So far it looks good to me, thank you very much!

I already pushed the ibus-table.pot file to master which contains the two new texts you added for your dark theme mode.

So you could add the missing Chinese translations here if you like:

https://translate.fedoraproject.org/projects/ibus-table/app/

**Comment by mike-fabian** [comment]
If you don’t have an account at https://translate.fedoraproject.org/projects/ibus-table/app/ yet, you can also write the translations for your two new strings here and I can paste it into Weblate then:

#. Translators: A combobox to choose whether
#. the color scheme for a dark theme should be used.
#: setup/main.py:1038
msgid "Use dark theme:"
msgstr ""

#. Translators: A tooltip for the label of the combobox to
#. choose whether the color scheme for a dark theme should
#. be used.
#: setup/main.py:1043
msgid "If yes, the color scheme for a dark theme will be used."
msgstr ""

**Comment by mozbugbox** [comment]
Thank you very much.

```
#. Translators: A combobox to choose whether
#. the color scheme for a dark theme should be used.
#: setup/main.py:1038
msgid "Use dark theme:"
msgstr "使用深色主题:"

#. Translators: A tooltip for the label of the combobox to
#. choose whether the color scheme for a dark theme should
#. be used.
#: setup/main.py:1043
msgid "If yes, the color scheme for a dark theme will be used."
msgstr "如果选择“是”，将使用匹配深色主题的色彩方案。"
```

**Comment by mike-fabian** [comment]
Great, thank you!

**Comment by mike-fabian** [comment]
Included in https://github.com/mike-fabian/ibus-table/releases/tag/1.13.0

Thank you very much for your great work!

**Comment by mike-fabian** [comment]
Included in https://github.com/mike-fabian/ibus-table/releases/tag/1.13.0

**Pull request closed without merging**
